import type { StatementData, Toolkit } from './types';

export const DISCLAIMER_TEXT = `
Welcome to the SME Business Model Advisor. Before you begin, please read the following disclaimer:

1.  **For Informational Purposes Only:** The advice, analysis, and reports generated by this AI tool are for informational and educational purposes only. They do not constitute professional, financial, or legal advice.

2.  **No Guarantees:** While we strive to provide accurate and helpful information, we make no guarantees regarding the completeness, reliability, or accuracy of the generated content. Business outcomes are influenced by numerous factors beyond the scope of this tool.

3.  **Your Responsibility:** You are solely responsible for any decisions or actions you take based on the information provided. We recommend consulting with qualified professionals before making any significant business decisions.

4.  **Data Privacy:** The information you enter is used to generate your report and is not stored or used for any other purpose. However, do not enter sensitive personal or confidential business information.

By clicking "I Accept," you acknowledge that you have read, understood, and agree to these terms.
`;

// Hypothetical data for Demo mode
export const hypotheticalData: StatementData = {
    customer: 'local families and office workers',
    problem: 'finding fresh, high-quality baked goods and coffee in the neighborhood',
    solution: 'offering artisanal breads, pastries, and specialty coffee in a cozy atmosphere',
    benefit: 'enjoy delicious, locally-made treats and a great community hub',
    revenueModel: 'direct sales of food and beverages',
    challenge: 'managing fluctuating ingredient costs and competing with larger chains',
    industry: 'Food & Beverage (Bakery)',
    country: 'Canada'
};

// Empty data for a new self-assessment
export const emptyData: StatementData = {
    customer: '',
    problem: '',
    solution: '',
    benefit: '',
    revenueModel: '',
    challenge: '',
    industry: '',
    country: ''
};

export const TOOLKITS: Toolkit[] = [
  {
    name: 'Business Model Canvas',
    description: 'A strategic management tool to quickly and easily define and communicate a business idea or concept. It is a one-page document which works through the fundamental elements of a business or product, structuring an idea in a coherent way.',
    source: 'Strategyzer, Alexander Osterwalder & Yves Pigneur, "Business Model Generation", 2010.',
    measures: 'Operationality, Commerciality, Viability'
  },
  {
    name: 'Lean Canvas',
    description: 'An adaptation of the Business Model Canvas by Ash Maurya that is tailored for startups and lean businesses. It replaces some elements with startup-focused metrics like Problem, Solution, Key Metrics, and Unfair Advantage.',
    source: 'Ash Maurya, "Running Lean", 2012. Inspired by Alexander Osterwalder\'s Business Model Canvas.',
    measures: 'Flexibility'
  },
  {
    name: 'Unique Selling Proposition Canvas (Value Proposition Canvas)',
    description: 'This canvas helps you ensure that your product or service is positioned around what the customer values and needs. It maps out customer jobs, pains, and gains against your value proposition\'s pain relievers and gain creators.',
    source: 'Strategyzer, Alexander Osterwalder, Yves Pigneur, Greg Bernarda, Alan Smith, "Value Proposition Design", 2014.',
    measures: '"Nichebility"'
  },
  {
    name: 'Platform Business Toolkit',
    description: 'A set of tools for designing and analyzing platform business models, which create value by facilitating exchanges between two or more interdependent groups, usually consumers and producers.',
    source: 'Sangeet Paul Choudary, "Platform Revolution", 2016.',
    measures: 'Agility'
  },
  {
    name: 'Product vs Market Matrix (Ansoff Matrix)',
    description: 'A strategic planning tool that provides a framework to help executives, senior managers, and marketers devise strategies for future growth. It presents four growth alternatives: market penetration, market development, product development, and diversification.',
    source: 'Igor Ansoff, "Corporate Strategy", 1965.',
    measures: 'Marketability'
  },
  {
    name: 'Customer vs Competition Matrix',
    description: 'A framework for analyzing a company\'s position in the market relative to its competitors and its target customers. It helps in identifying strategic moves based on competitive strengths and customer needs.',
    source: 'A conceptual tool widely used in strategic marketing, derived from various competitive analysis models.',
    measures: 'Feasibility'
  },
  {
    name: 'Three Phases of Corporate Transformation Toolkit',
    description: 'This model outlines the typical stages a company goes through during a major transformation: Mobilization (getting ready for change), Movement (implementing the change), and Sustain (embedding the change into the culture).',
    source: 'Based on concepts from John P. Kotter\'s work on change management, "Leading Change", 1996.',
    measures: 'Capacity and Capability'
  }
];